<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="container">

    <div class="page-header">
        <h1 class="display-2" style="font-weight: bold;">Search tag</h1>
    </div>

    <?php echo $this->getContent() ?>

    <?php
        echo $this->tag->form(
            [
                "tags/search",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            ]
        );
    ?>

    <div class="form-group">
        <label for="fieldId" class="col-sm-2 control-label">Id</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldLibelle" class="col-sm-2 control-label">Libelle</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["libelle", "size" => 30, "class" => "form-control", "id" => "fieldLibelle"]) ?>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-info"]) ?>
            <button type="button" class="btn btn-info" onClick='location.href="/tags/new"'>Create tag</button>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>
</div>