version: '2'

services:

  web:
    build:
        context: ./docker/web
        dockerfile: Dockerfile
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
        - ./nginx.conf:/etc/nginx/nginx.conf
    links:
        - php
        - db

  php:
    build:
        context: ./docker/php
        dockerfile: Dockerfile
    volumes:
        - ./code:/code
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: database
        DB_USER: admin
        DB_PASSWORD: test

  db:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    volumes:
      #- ./docker/mariadb/db-data:/var/lib/mysql
      - ./docker/mariadb/db-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_HOST=db
    restart: always
    ports:
        - 8890:80
    volumes:
        - /sessions
    links:
        - db
