<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="container">

    <p> <br></p>
    <button type="button" class="btn btn-dark" onClick='location.href="/users"'>Go back</button>

    <div class="row">
        <div class="page-header">
            <h1 class="display-2" style="font-weight: bold;">Create user</h1>
        </div>
    </div>

        <?php echo $this->getContent(); ?>

        <?php
            echo $this->tag->form(
                [
                    "users/create",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>

        <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
            value='<?php echo $this->security->getToken() ?>'/>

        <div class="form-group">
            <label for="fieldPseudo" class="col-sm-2 control-label">Pseudo</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["pseudo", "size" => 30, "class" => "form-control", "id" => "fieldPseudo"]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-info"]) ?>
            </div>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>
</div>