<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="container">
    <div class="page-header">
        <h1 class="display-2" style="font-weight: bold;">Search article</h1>
    </div>

    <?php echo $this->getContent() ?>

    <?php
        echo $this->tag->form(
            [
                "articles/search",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            ]
        );
    ?>

    <div class="form-group">
        <label for="fieldId" class="col-sm-2 control-label">Id</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldTitre" class="col-sm-2 control-label">Titre</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["titre", "size" => 30, "class" => "form-control", "id" => "fieldTitre"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldContenu" class="col-sm-2 control-label">Contenu</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["contenu", "size" => 30, "class" => "form-control", "id" => "fieldContenu"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldDatePublication" class="col-sm-2 control-label">Date Of Publication</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["date_publication", "type" => "date", "class" => "form-control", "id" => "fieldDatePublication"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldTagid" class="col-sm-2 control-label">TagId</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["tagId", "type" => "number", "class" => "form-control", "id" => "fieldTagid"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldUserid" class="col-sm-2 control-label">UserId</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["userId", "type" => "number", "class" => "form-control", "id" => "fieldUserid"]) ?>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-info"]) ?>
            <button type="button" class="btn btn-info" onClick='location.href="/articles/new"'>Create article</button>
        </div>
    </div>

    <?php echo $this->tag->endForm(); ?>
</div>