<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="container">
    <?php use Phalcon\Tag; ?>

    <p> <br></p>
    <button type="button" class="btn btn-dark" onClick='location.href="/articles/index"'>Go back</button>

    <div class="page-header">
        <h1>Search result</h1>
    </div>

    <?php echo $this->getContent(); ?>

    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                <th>Titre</th>
                <th>Contenu</th>
                <th>Date Of Publication</th>
                <th>TagId</th>
                <th>UserId</th>

                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $article): ?>
                <tr>
                    <td><?php echo $article->id ?></td>
                <td><?php echo $article->titre ?></td>
                <td><?php echo $article->contenu ?></td>
                <td><?php echo $article->date_publication ?></td>
                <td><?php echo $article->tagId ?></td>
                <td><?php echo $article->userId ?></td>

                    <td><?php echo $this->tag->linkTo(["articles/edit/" . $article->id, "Edit"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["articles/delete/" . $article->id, "Delete"]); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <button type="button" class="btn btn-info" onClick='location.href="/articles/new"'>Create</button>

    <div class="row">
        <div class="col-sm-1">
            <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                <?php echo $page->current, "/", $page->total_pages ?>
            </p>
        </div>
        <div class="col-sm-11">
        <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li><?php echo $this->tag->linkTo("articles/search", "First") ?></li>
                    <li><?php echo $this->tag->linkTo("articles/search?page=" . $page->before, "Previous") ?></li>
                    <li><?php echo $this->tag->linkTo("articles/search?page=" . $page->next, "Next") ?></li>
                    <li><?php echo $this->tag->linkTo("articles/search?page=" . $page->last, "Last") ?></li>
                </ul>
            </nav>
        </div>
    </div>
</div>