<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="container">

    <p> <br></p>
    <button type="button" class="btn btn-dark" onClick='location.href="<?php echo $this->url->get("tags/index");?>"'>Go back</button>

    <div class="page-header">
        <h1 class="display-2" style="font-weight: bold;">Search result</h1>
    </div>

    <?php echo $this->getContent(); ?>

    <div class="row">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                <th>Libelle</th>

                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $tag): ?>
                <tr>
                    <td><?php echo $tag->id ?></td>
                <td><?php echo $tag->libelle ?></td>

                    <td><?php echo $this->tag->linkTo(["tags/edit/" . $tag->id, "Edit"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["tags/delete/" . $tag->id, "Delete"]); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <button type="button" class="btn btn-info" onClick='location.href="<?php echo $this->url->get("tags/new");?>"'>Create</button>

    <div class="row">
        <div class="col-sm-1">
            <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                <?php echo $page->current, "/", $page->total_pages ?>
            </p>
        </div>
        <div class="col-sm-11">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li><?php echo $this->tag->linkTo("tags/search", "First") ?></li>
                    <li><?php echo $this->tag->linkTo("tags/search?page=" . $page->before, "Previous") ?></li>
                    <li><?php echo $this->tag->linkTo("tags/search?page=" . $page->next, "Next") ?></li>
                    <li><?php echo $this->tag->linkTo("tags/search?page=" . $page->last, "Last") ?></li>
                </ul>
            </nav>
        </div>
    </div>
</div>